---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# flipr

<!-- badges: start -->
<!-- badges: end -->

The goal of flipr is aid the user in inverting and flipping data frames. This includes flipping rows and columns, inverting the order of rows, and inverting the order of columns. Included is an example dataset.

## Installation

You can install the released version of flipr from [Github](https://github.com) with:

``` {}
devtools::install_github("fieldima/flipr", ref = "0.2.0")

```
## Example

This is a basic example of when you would use flipr:

```{r example}
library(flipr)

#Packaged with flipr is a set of simulation data that needs to be flipped.
sim <- simulation_data

#To flip the rows and columns, simply use flip()
flip(sim)

#This package also gives the user the ability to invert the order of rows or columns
invert_row(sim)
invert_col(sim)

#Finally, all functions in this package can output data in the form of data frames, tibbles, or data tables
flip(sim, "TB")
flip(sim, "DT")

invert_row(sim, "DF")
invert_row(sim, "TB")

invert_col(sim, "DT")
```

